### ISSUE TITLE
Endless loading screen

### ISSUE THREAD

**Issue by SpaghettDev** [DottieDot/GTAV-NativeDB#31]
I'm not sure why, but going to https://nativedb.dotindustries.dev results in an endless loading screen.
Opening that link in a private window works fine and redirects to https://gta5.nativedb.dotindustries.dev/natives.
I think it might have to do with upload a special.json cause that's the only difference.

Using Firefox Nightly Version 110.0a1.

**Comment by SpaghettDev** [comment]
After some testing, the issue is 100% related to uploading a special.json
Tried opening https://nativedb.dotindustries.dev in a browser that has never visited it (Chrome Version 108.0.5359.125), worked fine.
After uploading a special.json however, closing the tab then opening another one results in an endless loading screen.

**Comment by DottieDot** [comment]
The problem is that the web browser is serving the cached/installed PWA instead of following the redirect. Clearing the site data will fix it.

As for why using an older version of the PWA will result in an infinite loading screen, I've no idea.

I'll see if I can fix it by changing the DNS settings; if not, I'll remove the redirect and serve the content on nativedb.dotindustries.dev too.

**Comment by SpaghettDev** [comment]
Oh, alright. I guess I'll close this issue for now.
